image:  mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
    - build
    - package
   
build:  
    stage: build
    before_script:
      - "dotnet restore ./IrrationalEngine/IeUtils/IeUtils.csproj -v n"
      - "dotnet restore ./IrrationalEngine/IeCoreEntites/IeCoreEntites.csproj -v n"
      - "dotnet restore ./IrrationalEngine/IeCoreInterfaces/IeCoreInterfaces.csproj -v n"
      - "dotnet restore ./IrrationalEngine/IeCoreOpengl/IeCoreOpengl.csproj -v n"
      - "dotnet restore ./IrrationalEngine/IeCore/IeCore.csproj -v n"
    artifacts:
      paths: 
      - "./IrrationalEngine/IeCore/"
    script:
        - "dotnet build ./IrrationalEngine/IeCore/IeCore.csproj -c Release -v n" 