image:  mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
    - build
    -package

before_script:
    - "dotnet restore ./IrrationalEngine/IeUtils/IeUtils.csproj -v n"
    - "dotnet restore ./IrrationalEngine/IeCoreEntites/IeCoreEntites.csproj -v n"
    - "dotnet restore ./IrrationalEngine/IeCoreInterfaces/IeCoreInterfaces.csproj -v n"
    - "dotnet restore ./IrrationalEngine/IeCoreOpengl/IeCoreOpengl.csproj -v n"
    - "dotnet restore ./IrrationalEngine/IeCore/IeCore.csproj -v n"
   
build:
    stage: build
    script:
        - "dotnet build ./IrrationalEngine/IeCore/IeCore.csproj -c Release -v n" 

package:
  stage: package
  script: tar -cfz packaged.tar.bz2 ./IrrationalEngine/IeCore/bin/Release/netcoreapp3.1 
  artifacts:
    paths:
    - packaged.tar.gz
    expire_in: 1 month