image: microsoft/dotnet:latest

stages:
    - build

before_script:
    - "dotnet restore ./IrrationalEngine -v n"

build:
    stage: build
    script:
        - "dotnet build ./IrrationalEngine -c Release|Any CPU -v n" 