image:  mcr.microsoft.com/dotnet/core/sdk:3.0

stages:
    - build

before_script:
    - "dotnet restore ./IrrationalEngine/IeUtils/IeUtils.csproj -v d"
    - "dotnet restore ./IrrationalEngine/IeCoreEntites/IeCoreEntites.csproj -v d"
    - "dotnet restore ./IrrationalEngine/IeCoreInterfaces/IeCoreInterfaces.csproj -v d"
    - "dotnet restore ./IrrationalEngine/IeCoreOpengl/IeCoreOpengl.csproj -v d"
    - "dotnet restore ./IrrationalEngine/IeCore/IeCore.csproj -v d"
    - "dotnet restore ./IrrationalEngine/IrrationalEngineCore/IrrationalEngineCore.csproj -v d"
    - "dotnet restore ./IrrationalEngine/IrrationalEngineEditor/IrrationalEngineEditor.csproj -v d"
    - "dotnet restore ./IrrationalEngine/IrrationalEndgineEditorWpfUi/IrrationalEndgineEditorWpfUi.csproj -v d"

build:
    stage: build
    script:
        - "dotnet build ./IrrationalEngine -c Release|Any CPU -v n" 