image:  mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
    - build
    - cleanup
   
build:  
    stage: build
    cache:
      paths:
        - "~/.local/share/NuGet/plugins-cache"
    before_script:
      - "dotnet restore ./IrrationalEngine/IeUtils/IeUtils.csproj -v n"
      - "dotnet restore ./IrrationalEngine/IeCoreEntites/IeCoreEntites.csproj -v n"
      - "dotnet restore ./IrrationalEngine/IeCoreInterfaces/IeCoreInterfaces.csproj -v n"
      - "dotnet restore ./IrrationalEngine/IeCoreOpengl/IeCoreOpengl.csproj -v n"
      - "dotnet restore ./IrrationalEngine/IeCore/IeCore.csproj -v n"    
    script:
        - "dotnet build ./IrrationalEngine/IeCore/IeCore.csproj -c Release -v n" 
    artifacts:
      paths: 
      - $bin_location
      expire_in: 1 month

cleanup:
  stage: cleanup
  script:
    - "rm -r ./IrrationalEngine"
    - "ls ~/.local/share/NuGet/plugins-cache"
  when: always